### PR TITLE
Add "Verification" section to the "Download" page

### PR DESCRIPTION
**Pull request by selliott512**
Let people know how they can verify the downloaded files.

---

Is this too much? I wasn't sure it was worth creating another page. I tried state the fundamental information succinctly. And I know it's reassuring to me to have a way of making sure I got the right thing when downloading something new.

Also, for me, the HTML and TXT were out of sync, but it seems like it's mostly white space, so I wonder if it's a AsciiDoc issue. I synced them with a separate commit first so you can see the real work separately.

verification

### CODE REVIEW

**Comment by mc776** [comment]
Can we just post the checksums of the zip files instead? My big concern here is just how maintainable this will be as people come and go over the years (cf. nobody actively involved even knew what the download.json file was for and we almost deleted it until someone got curious enough to check some really old commits)

**Comment by selliott512** [comment]
Sure, I'll work on something. I hesitated because this new `Verification` section, which mostly only security nerds will read, is just as large as the `Game Data` section that actually matters. 

Regarding `download.json` I'm documenting everything relevant to a release, so we shouldn't forget about it in the future, but that being said a JSON file is a bit obscure for the average user. They deserve something easier to understand, like the hashes directly, as you suggest. I'll take another shot at it.

The key table can probably just replaced with a link to the `keys` directory since the table is more than what is needed (although part of my motivation was making them findable by Google).

**Comment by mc776** [comment]
> but it seems like it's mostly white space, so I wonder if it's a AsciiDoc issue

In a way, yes, but maybe not what you're thinking:
```
0 upgraded, 80 newly installed, 0 to remove and 16 not upgraded.
Need to get 361 MB of archives.
After this operation, 763 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

> 80 newly installed

> 763 MB

**Comment by selliott512** [comment]
What do you think of this?:
 
hashes

Shorter. No mention of `download.json`. I know all three hashes may seem excessive, but I know that I sometimes hash files, and then search for the hash to see if it's ok. Others might do likewise. And some folks may only have one of the three hash tools installed.

**Comment by selliott512** [comment]
Also, I've updated the "Release Checklist" with a one liner bash command to generate the hash part of the table - maintainers won't have to get each hash manually.

**Comment by mc776** [comment]
Is there some way to change the alt texts back to "Freedoom screenshot" (Or maybe "Freedoom Phase 1 screenshot", etc.)? File names are not good for screen readers (or anyone else who's looking at the alt text for whatever reason).

**Comment by selliott512** [comment]
More like this?:

hashes-descriptive-names

I just took the first column from the previous table, so it's obvious now how they relate. I let them continue to be links since that seems convenient.

**Comment by mc776** [comment]
How does this look on mobile? So far the site's been pretty decent about that...

**Comment by selliott512** [comment]
Good question. Not great. Here it is on My Pixel 2 XL where the long SHA256 hash extends to the right, and caused everything else to be smaller.

verification-andcroid

Let me think about it for a bit.

**Comment by selliott512** [comment]
I almost give up. How about a sentence directing them to the release page?:

verify-sentence

I figured there was not much harm in uploading the keys. They are public keys - no security concern.

**Comment by mc776** [comment]
> How about a sentence directing them to the release page?

I think this is the best solution - and cuts down on the amount of stuff we need to copypaste too!

**Pull request merged**
