### PR TITLE
Remove download.json

### PR DESCRIPTION
**Pull request by selliott512**
Remove download.json since nothing references it.

----

Noting references this file, and Googling `download.json` does not find anything relevant, yet it was updated every release, which I'd prefer to not do. Am I missing something?

### CODE REVIEW

**Comment by mc776** [comment]
Shouldn't this checksum information be on the download page?

**Comment by mc776** [comment]
https://github.com/freedoom/freedoom.github.io/issues/4

**Comment by mc776** [comment]
Doomseeker still seems to exist so let's keep supporting it... and since I'm here I'll give updating it a try.

**Comment by selliott512** [comment]
@mc776 Nice. You cracked the code of `download.json` by finding that issue. I'll add something about it to the [release checklist](https://github.com/freedoom/freedoom/issues/400).

**Pull request closed without merging**
